## Simulation exercises

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

np.random.seed(50)

### 1. How likely is it that you roll doubles when rolling two dice?

In [3]:
n_trials = 10**5
n_rolls = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_rolls).reshape(n_trials, n_rolls)
rolls

array([[1, 6],
       [4, 1],
       [2, 3],
       ...,
       [2, 6],
       [2, 1],
       [6, 5]])

In [79]:
(pd.DataFrame(rolls)[0] == pd.DataFrame(rolls)[1]).mean()

0.16706

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [13]:
n_flips = columns = 8
n_trials = rows = 10**5
all_flips = np.random.choice(['Heads', 'Tails'], size = (10**5, 8))
all_flips[0:7]

array([['Heads', 'Tails', 'Tails', 'Heads', 'Heads', 'Heads', 'Heads',
        'Heads'],
       ['Tails', 'Heads', 'Heads', 'Tails', 'Heads', 'Tails', 'Heads',
        'Tails'],
       ['Heads', 'Heads', 'Tails', 'Tails', 'Heads', 'Tails', 'Tails',
        'Tails'],
       ['Heads', 'Heads', 'Tails', 'Tails', 'Tails', 'Tails', 'Heads',
        'Heads'],
       ['Tails', 'Heads', 'Tails', 'Heads', 'Heads', 'Tails', 'Heads',
        'Heads'],
       ['Heads', 'Tails', 'Tails', 'Heads', 'Heads', 'Tails', 'Heads',
        'Heads'],
       ['Heads', 'Tails', 'Heads', 'Tails', 'Heads', 'Tails', 'Heads',
        'Tails']], dtype='<U5')

In [14]:
(all_flips == 'Heads')[0:5]

array([[ True, False, False,  True,  True,  True,  True,  True],
       [False,  True,  True, False,  True, False,  True, False],
       [ True,  True, False, False,  True, False, False, False],
       [ True,  True, False, False, False, False,  True,  True],
       [False,  True, False,  True,  True, False,  True,  True]])

In [15]:
len(all_flips == 'Heads')

100000

In [86]:
(good_flip.sum(axis=1) >= 3).mean()

0.85462

#### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

### Example with one pick

In [90]:
n_picks = columns = 2
n_trials = rows = 1
p_pick = .5

In [92]:
data = np.random.random((rows, columns))
data

array([[0.08224087, 0.23166557]])

In [93]:
ds_student_billboard = data < p_pick

In [94]:
ds_student_billboard.sum(axis=1)

array([2])

In [101]:
(ds_student_billboard.sum(axis=1) == 2).mean()

0.2482

### Example with 10,000,000 picks

In [1]:
n_picks = columns = 2
n_trials = rows = 10**7
p_pick = .5

In [3]:
data = np.random.random((rows, columns))
data

array([[0.86375999, 0.28490597],
       [0.07325639, 0.7632372 ],
       [0.45271906, 0.54229687],
       ...,
       [0.39422878, 0.80384332],
       [0.49698887, 0.83156291],
       [0.14208256, 0.86654939]])

In [4]:
ds_student_billboard = data < p_pick

In [5]:
ds_student_billboard.sum(axis=1)

array([1, 1, 1, ..., 1, 1, 1])

In [6]:
(ds_student_billboard.sum(axis=1) == 2).mean()

0.2497769

#### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)