## Simulation exercises

In [2]:
%matplotlib inline
import numpy as np
import pandas as pd

np.random.seed(29)

#### 1. How likely is it that you roll doubles when rolling two dice?

In [73]:
n_trials = 10**5
n_rolls = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_rolls).reshape(n_trials, n_rolls)
rolls

array([[2, 3],
       [2, 4],
       [6, 4],
       ...,
       [3, 1],
       [3, 6],
       [1, 2]])

In [79]:
(pd.DataFrame(rolls)[0] == pd.DataFrame(rolls)[1]).mean()

0.16706

#### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [66]:
n_flips = columns = 8
n_trials = rows = 10**5
p_flip = .5

In [67]:
data = np.random.random((rows, columns))
data

array([[0.34350279, 0.46872199, 0.62307566, ..., 0.34552021, 0.85025438,
        0.68426358],
       [0.11116887, 0.26073575, 0.92681934, ..., 0.17709068, 0.79597504,
        0.1781185 ],
       [0.3096851 , 0.45641581, 0.1368052 , ..., 0.90814205, 0.36709877,
        0.46369507],
       ...,
       [0.74326292, 0.38304466, 0.984331  , ..., 0.54102893, 0.26555776,
        0.80292954],
       [0.84927074, 0.5164997 , 0.22938739, ..., 0.36733016, 0.03632645,
        0.61638297],
       [0.13699901, 0.46277923, 0.57159378, ..., 0.58121855, 0.35342604,
        0.10127986]])

In [68]:
good_flip = data < p_flip
good_flip

array([[ True,  True, False, ...,  True, False, False],
       [ True,  True, False, ...,  True, False,  True],
       [ True,  True,  True, ..., False,  True,  True],
       ...,
       [False,  True, False, ..., False,  True, False],
       [False, False,  True, ...,  True,  True, False],
       [ True,  True, False, ..., False,  True,  True]])

In [71]:
good_flip.sum(axis=1)

array([4, 5, 5, ..., 2, 3, 5])

#### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

#### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)